### ISSUE TITLE
Fiatlux installation via conda is broken for MacOS

### ISSUE THREAD

**Issue by niclaurenti** [scarrazza/fiatlux#6]
Opening this issue since `fiatlux` installation via `conda` is broken for MacOS:
the problem is that when he tries to resolve the dependencies it runs forever and in the end it crashes.

I will upload the error as soon as I will have it.

**Comment by niclaurenti** [comment]
This is the first part of the error

```
UnsatisfiableError: The following specifications were found to be incompatible with a past
explicit spec that is not an explicit spec in this operation (libcxx):

  - fiatlux -> libcxx[version='>=14.0.4|>=14.0.6']
  - fiatlux -> python[version='>=3.8,<3.9.0a0'] -> libcxx[version='>=10.0.0|>=12.0.0|>=4.0.1|>=11.1.0|>=11.0.1|>=11.0.0|>=10.0.1|>=9.0.1|>=9.0.0']
  - fiatlux -> python[version='>=3.8,<3.9.0a0'] -> sqlite[version='>=3.30.0,<4.0a0|>=3.30.1,<4.0a0|>=3.31.1,<4.0a0|>=3.32.3,<4.0a0|>=3.33.0,<4.0a0|>=3.35.4,<4.0a0|>=3.36.0,<4.0a0|>=3.37.2,<4.0a0|>=3.39.3,<4.0a0|>=3.40.0,<4.0a0|>=3.40.1,<4.0a0|>=3.37.1,<4.0a0|>=3.37.0,<4.0a0|>=3.35.5,<4.0a0|>=3.34.0,<4.0a0|>=3.39.2,<4.0a0|>=3.38.3,<4.0a0|>=3.38.2,<4.0a0|>=3.38.5,<4.0a0|>=3.39.1,<4.0a0']
```

the rest is huge.

**Comment by niclaurenti** [comment]
```
The following specifications were found to be incompatible with your system:

  - feature:/osx-64::__osx==10.16=0
  - feature:/osx-64::__unix==0=0
  - feature:|@/osx-64::__osx==10.16=0
  - feature:|@/osx-64::__unix==0=0
  - banana-hep -> click[version='>=8.0.3,<9.0.0'] -> __unix
  - banana-hep -> click[version='>=8.0.3,<9.0.0'] -> __win
  - banana-hep -> ipython[version='>=8.1.0,<9.0.0'] -> __osx[version='>=10.11|>=10.12']
  - black -> click[version='>=8.0.0'] -> __unix
  - black -> click[version='>=8.0.0'] -> __win
  - click -> __unix
  - click -> __win
  - google-auth-oauthlib -> click[version='>=6.0.0'] -> __unix
  - google-auth-oauthlib -> click[version='>=6.0.0'] -> __win
  - grpcio -> __osx[version='>=10.10|>=10.9']
  - hypothesis -> click[version='>=7.0'] -> __unix
  - hypothesis -> click[version='>=7.0'] -> __win
  - ipdb -> ipython -> __osx
  - ipdb -> ipython -> __win
  - ipython -> __osx
  - ipython -> __win
  - matplotlib-base -> __osx[version='>=10.11|>=10.12']
  - matplotlib-inline -> ipython -> __osx
  - matplotlib-inline -> ipython -> __win
  - matplotlib[version='>=3.3.0'] -> matplotlib-base[version='>=3.7.1,<3.7.2.0a0'] -> __osx[version='>=10.11|>=10.12']
  - networkx -> matplotlib-base[version='>=3.4'] -> __osx[version='>=10.11|>=10.12']
  - pysocks -> __unix
  - pysocks -> __win
  - seaborn -> matplotlib-base[version='>=3.1,!=3.6.1'] -> __osx[version='>=10.11|>=10.12']
  - tensorboard -> grpcio[version='>=1.24.3'] -> __osx[version='>=10.10|>=10.9']
  - tensorflow -> tensorflow-base==2.11.0=cpu_py39ha6e17e1_0 -> __osx[version='>=10.10|>=10.13|>=10.9']
  - tensorflow-base -> __osx[version='>=10.13']
  - tensorflow-base -> grpcio -> __osx[version='>=10.10|>=10.9']
  - tensorflow-estimator -> grpcio[version='>=1.8.6'] -> __osx[version='>=10.10|>=10.9|>=10.13']
  - urllib3 -> pysocks[version='>=1.5.6,<2.0,!=1.5.7'] -> __unix
  - urllib3 -> pysocks[version='>=1.5.6,<2.0,!=1.5.7'] -> __win

Your installed version is: 10.16
```

**Comment by alecandido** [comment]
@scarrazza the problem is really about conflicting dependencies.

It is not 100% clear to me, because the Conda message is rather messy, but at least there are some deps that require `__unix` or `__win` (like `click`), and they do not have an option at all for `__osx`.

**Comment by scarrazza** [comment]
My suggestion is to someone with a mac try to clone https://github.com/conda-forge/fiatlux-feedstock/ and execute the conda build locally. From the recipe there is no evidence of a mac specific package conflict, see here https://github.com/conda-forge/fiatlux-feedstock/blob/8fd84d53410075e8a334a43fb580d5db4a2c7f9b/recipe/meta.yaml#L17.

**Comment by alecandido** [comment]
However, I do not understand how `fiatlux` can have dependency issues, without having any dependency...

**Comment by niclaurenti** [comment]
The error is
```
scikit-build could not get a working generator for your system. Aborting build.

  Building MacOSX wheels for Python 3.10 requires XCode.
  Get it here:

    https://developer.apple.com/xcode/

  ********************************************************************************
  error: subprocess-exited-with-error
  
  × Building wheel for fiatlux (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /Users/niccololaurenti/miniconda3/conda-bld/fiatlux_1679501733453/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/bin/python /Users/niccololaurenti/miniconda3/conda-bld/fiatlux_1679501733453/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py build_wheel /tmp/tmplnty50kz
  cwd: /Users/niccololaurenti/miniconda3/conda-bld/fiatlux_1679501733453/work
  Building wheel for fiatlux (pyproject.toml): finished with status 'error'
  ERROR: Failed building wheel for fiatlux
Failed to build fiatlux
ERROR: Could not build wheels for fiatlux, which is required to install pyproject.toml-based projects
Exception information:
Traceback (most recent call last):
  File "$PREFIX/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 160, in exc_logging_wrapper
    status = run_func(*args)
  File "$PREFIX/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 247, in wrapper
    return func(self, options, args)
  File "$PREFIX/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 477, in run
    raise InstallationError(
pip._internal.exceptions.InstallationError: Could not build wheels for fiatlux, which is required to install pyproject.toml-based projects
Removed build tracker: '/private/tmp/pip-build-tracker-ts1oapy7'
Traceback (most recent call last):
  File "/Users/niccololaurenti/miniconda3/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/Users/niccololaurenti/miniconda3/lib/python3.10/site-packages/conda_build/cli/main_build.py", line 495, in main
    execute(sys.argv[1:])
  File "/Users/niccololaurenti/miniconda3/lib/python3.10/site-packages/conda_build/cli/main_build.py", line 475, in execute
    outputs = api.build(
  File "/Users/niccololaurenti/miniconda3/lib/python3.10/site-packages/conda_build/api.py", line 180, in build
    return build_tree(
  File "/Users/niccololaurenti/miniconda3/lib/python3.10/site-packages/conda_build/build.py", line 3097, in build_tree
    packages_from_this = build(metadata, stats,
  File "/Users/niccololaurenti/miniconda3/lib/python3.10/site-packages/conda_build/build.py", line 2209, in build
    utils.check_call_env(cmd, env=env, rewrite_stdout_env=rewrite_env,
  File "/Users/niccololaurenti/miniconda3/lib/python3.10/site-packages/conda_build/utils.py", line 402, in check_call_env
    return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)
  File "/Users/niccololaurenti/miniconda3/lib/python3.10/site-packages/conda_build/utils.py", line 382, in _func_defaulting_env_to_os_environ
    raise subprocess.CalledProcessError(proc.returncode, _args)
subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/Users/niccololaurenti/miniconda3/conda-bld/fiatlux_1679501733453/work/conda_build.sh']' returned non-zero exit status 1.
```
I tried to run
```
export CONDA_BUILD_SYSROOT=<path_to_root_conda_directory>/MacOSX10.9.sdk
```
but nothing changed

**Comment by niclaurenti** [comment]
@scarrazza @AleCandido the problem was the python version: I made a new conda environment that uses python 3.10 (while previously I was using 3.8) and it works without any problems

**Comment by alecandido** [comment]
Ok, but then are we dropping support also for py3.8? (at least on MacOS)
